//
//  GPSLocalizationView.swift
//  STEP Navigation
//
//  Created by Evelyn on 4/24/23.
//

import SwiftUI
import AuthenticationServices

struct GPSLocalizationView: View {
    @ObservedObject var database = FirebaseManager.shared
    @ObservedObject var positionModel = PositioningModel.shared
    @ObservedObject var authHandler = AuthHandler.shared
    let minimumGeoLocationAccuracy: GeoLocationAccuracy = .coarse
    
    @State private var isAnimating = false
    
    var body: some View {
        if authHandler.currentUID == nil {
            SignInWithApple()
                .frame(width: 280, height: 60)
                .onTapGesture(perform: authHandler.startSignInWithAppleFlow)
        } else {
            NavigationStack {
                ScreenTitleComponent(titleText: "STEP Navigation", subtitleText: "Precise Short Distance Navigation for the Blind and Visually Impaired")
                .navigationBarBackButtonHidden()
                //hides the autogenerated back button on the screen
                .padding(.top, 60)
                .background(AppColor.accent)
                //added padding and background to compensate for the back button being hidden
                
                ZStack {
                    Rectangle()
                        .fill(AppColor.light)
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                    
                    if positionModel.geoLocalizationAccuracy.isAtLeastAsGoodAs(other: minimumGeoLocationAccuracy) {
                        if positionModel.currentLatLon != nil {
                            VStack {
                                VStack {
                                    HStack {
                                        Text("Multiple Destinations Found")
                                            .bold()
                                            .foregroundColor(AppColor.dark)
                                            .font(.title)
                                            .multilineTextAlignment(.center)
                                    }
                                    .frame(maxWidth: .infinity)
                                    .frame(height: 200)
                                    .padding(.horizontal)
                                    
                                    SmallButtonComponent_NavigationLink(destination: {
                                                        DestinationTypesView()
                                                    }, label: "Next")
                                }
                                .frame(maxWidth: .infinity)
                                .padding()
                                
                                Spacer()
                            }
                            
                        } else {
                            Text("Inconsistent State.  Contact your developer")
                        }
                    } else  {
                        VStack {
                            VStack {
                                HStack {
                                    Text("Finding Destinations Near You")
                                        .foregroundColor(AppColor.dark)
                                        .bold()
                                        .font(.title)
                                        .multilineTextAlignment(.center)
                                }
                                .frame(maxWidth: .infinity)
                                .frame(height: 200)
                                .padding(.horizontal)
                                
                                ZStack {
                                    Circle()
                                        .stroke(AppColor.dark, lineWidth: 5)
                                        .frame(width: 100, height: 100)
                                        .opacity(0.25)
                                    Circle()
                                        .trim(from: 0.25, to: 1)
                                        .stroke(AppColor.dark, style: StrokeStyle(lineWidth: 5, lineCap: .round))
                                        .frame(width: 100, height: 100)
                                        .rotationEffect(.degrees(isAnimating ? 360 : 0))
                                        .onAppear {
                                            withAnimation(Animation.linear(duration: 1).repeatForever(autoreverses: false)) {
                                                self.isAnimating = true
                                            }
                                        }
                                    
                                }
                                .frame(height: 100)
                                .padding()
                                .drawingGroup()
                                
                                Spacer()
                            }
                            Spacer()
                        }
                        .frame(maxWidth: .infinity)
                        .padding()
                    }
                }
                .background(AppColor.accent)
                .onAppear() {
                    positionModel.startCoarsePositioning()
                }
            }
            .accentColor(AppColor.dark)
        }
    }
}
