//
//  AuthHandler.swift
//  STEP Navigation
//
//  Created by Paul Ruvolo on 5/10/23.
//

import Foundation
import FirebaseCore
import FirebaseAuth
import CryptoKit
import AuthenticationServices
import SwiftUI


/// This class interacts with both the Apple Sign-In capability and FirebaseAuth.  The class has a field that can be observed in order to get the currently logged-in user (nil if no login).
class AuthHandler: NSObject, ObservableObject, ASAuthorizationControllerDelegate {
    /// The handle to the singleton instance of this class
    public static var shared = AuthHandler()
    /// Unhashed nonce.
    private var currentNonce: String?
    /// Handle to Firebase authentication
    private let firebaseAuth = Auth.auth()
    
    /// the current user ID.  If the user is not properly authenticated, this value will be nil.  This ID is a Firebase user ID (not specific to any particular authentication provider)
    @Published var currentUID: String?
    
    /// default initializer (this should not be called directly)
    private override init() {
        currentUID = firebaseAuth.currentUser?.uid
        super.init()
        createAuthListener()
    }
    
    /// This function responds to authentication state changes so the information in `currentUID`
    private func createAuthListener() {
        firebaseAuth.addStateDidChangeListener() { (auth, user) in
            self.currentUID = user?.uid
            print("currentUID \(self.currentUID)")
        }
    }
    
    /// Creates a nonce for use with the Apple OAuth flow
    /// - Parameter length: the length of the nonce
    /// - Returns: the nonce
    private func randomNonceString(length: Int = 32) -> String {
      precondition(length > 0)
      var randomBytes = [UInt8](repeating: 0, count: length)
      let errorCode = SecRandomCopyBytes(kSecRandomDefault, randomBytes.count, &randomBytes)
      if errorCode != errSecSuccess {
        fatalError(
          "Unable to generate nonce. SecRandomCopyBytes failed with OSStatus \(errorCode)"
        )
      }

      let charset: [Character] =
        Array("0123456789ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvwxyz-._")

      let nonce = randomBytes.map { byte in
        // Pick a random character from the set, wrapping around if needed.
        charset[Int(byte) % charset.count]
      }

      return String(nonce)
    }
    
    /// Hashes using the SHA256 algorithm
    /// - Parameter input: the string to hash
    /// - Returns: the hashed string
    private func sha256(_ input: String) -> String {
      let inputData = Data(input.utf8)
      let hashedData = SHA256.hash(data: inputData)
      let hashString = hashedData.compactMap {
        String(format: "%02x", $0)
      }.joined()

      return hashString
    }
    
    /// Begins the Apple sign-in flow by creating a request with the `ASAuthorizationAppleIDProvider`
    /// `createRequest` function.
    func startSignInWithAppleFlow() {
      let nonce = randomNonceString()
      currentNonce = nonce
      let appleIDProvider = ASAuthorizationAppleIDProvider()
      let request = appleIDProvider.createRequest()
      request.requestedScopes = [.fullName, .email]
      request.nonce = sha256(nonce)

      let authorizationController = ASAuthorizationController(authorizationRequests: [request])
      authorizationController.delegate = self
      authorizationController.performRequests()
    }
    
    /// A callback function that indicates authentication was successful.
    /// - Parameters:
    ///   - controller: the controller that was used for authentication
    ///   - authorization: the authorization generated by the Apple authentication procedure
    func authorizationController(controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization) {
      if let appleIDCredential = authorization.credential as? ASAuthorizationAppleIDCredential {
        guard let nonce = currentNonce else {
          fatalError("Invalid state: A login callback was received, but no login request was sent.")
        }
        guard let appleIDToken = appleIDCredential.identityToken else {
          print("Unable to fetch identity token")
          return
        }
        guard let idTokenString = String(data: appleIDToken, encoding: .utf8) else {
          print("Unable to serialize token string from data: \(appleIDToken.debugDescription)")
          return
        }
        // Initialize a Firebase credential, including the user's full name.
        let credential = OAuthProvider.appleCredential(withIDToken: idTokenString,
                                                       rawNonce: nonce,
                                                       fullName: appleIDCredential.fullName)
        // Sign in with Firebase.
        Auth.auth().signIn(with: credential) { (authResult, error) in
          if let error = error {
            // Error. If error.code == .MissingOrInvalidNonce, make sure
            // you're sending the SHA256-hashed nonce as a hex string with
            // your request to Apple.
            print(error.localizedDescription)
            return
          }
          // User is signed in to Firebase with Apple.
          // ...
        }
      }
    }
    
    /// A callback function that is called when the authentication request failed
    /// - Parameters:
    ///   - controller: the controller that requested the authentication with Apple
    ///   - error: the error that occurred
    func authorizationController(controller: ASAuthorizationController, didCompleteWithError error: Error) {
      // Handle error.
      print("Sign in with Apple errored: \(error)")
    }
}


/// A wrapper for the "Sign in with Apple" button for SwiftUI
struct SignInWithApple: UIViewRepresentable {
    /// Creates the UIView as part of the `UIViewRepresentable` protocol
    /// - Parameter context: the context for creating the UIView
    /// - Returns: the UIView
    func makeUIView(context: Context) -> ASAuthorizationAppleIDButton {
        return ASAuthorizationAppleIDButton()
    }
    
    ///
    /// - Parameters:
    ///   - uiView: a handle to the ASAuthorizationAppleIDButton
    ///   - context: the context in which the update is occurring.
    func updateUIView(_ uiView: ASAuthorizationAppleIDButton, context: Context) {
        // no updates
    }
}
